name: Split package

on:
  workflow_call:
    inputs:
      package:
        description: Package repository and directory name
        required: true
        type: string
    secrets:
      MONOREPO_SPLIT_TOKEN:
        required: true

jobs:
  split:
    name: ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out monorepo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Split branch
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        uses: symplify/monorepo-split-github-action@v2.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLIT_TOKEN }}
        with:
          branch: master
          package_directory: app-modules/${{ inputs.package }}
          repository_organization: misaf
          repository_name: ${{ inputs.package }}
          user_name: misaf
          user_email: misaf.1990@gmail.com

      - name: Split tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: symplify/monorepo-split-github-action@v2.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLIT_TOKEN }}
        with:
          branch: master
          tag: ${{ github.ref_name }}
          package_directory: app-modules/${{ inputs.package }}
          repository_organization: misaf
          repository_name: ${{ inputs.package }}
          user_name: misaf
          user_email: misaf.1990@gmail.com

      - name: Create release for split package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLIT_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --repo "misaf/${{ inputs.package }}" --generate-notes
