name: Split packages

concurrency:
  group: split-packages
  cancel-in-progress: false

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  foundation:
    uses: ./.github/workflows/split-package.yml
    with:
      package: vendra-testing
    secrets: inherit

  core:
    needs: foundation
    strategy:
      fail-fast: false
      matrix:
        package:
          - vendra-api
          - vendra-localization
          - vendra-support
    uses: ./.github/workflows/split-package.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit

  domain-base:
    needs: core
    strategy:
      fail-fast: false
      matrix:
        package:
          - vendra-activity-log
          - vendra-attribute
          - vendra-geo
          - vendra-multimedia
          - vendra-tagger
          - vendra-tenant
    uses: ./.github/workflows/split-package.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit

  domain:
    needs: domain-base
    strategy:
      fail-fast: false
      matrix:
        package:
          - vendra-attribute-api
          - vendra-currency
          - vendra-custom-page
          - vendra-faq
          - vendra-language
          - vendra-multimedia-api
          - vendra-transaction
          - vendra-user
    uses: ./.github/workflows/split-package.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit

  features:
    needs: domain
    strategy:
      fail-fast: false
      matrix:
        package:
          - vendra-affiliate
          - vendra-authify-log
          - vendra-blog
          - vendra-faq-api
          - vendra-newsletter
          - vendra-permission
          - vendra-product
    uses: ./.github/workflows/split-package.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit

  applications:
    needs: features
    strategy:
      fail-fast: false
      matrix:
        package:
          - vendra-blog-api
          - vendra-product-api
          - vendra-subscription
          - vendra-user-profile
    uses: ./.github/workflows/split-package.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit
