name: Validate application container

on:
  pull_request:
  push:
    branches:
      - 1.x

jobs:
  entrypoint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate entrypoint shell script
        run: sh -n docker-entrypoint.sh
